name: rna-vel-benchmark-env
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python==3.11
  - pip
  - pydantic >=2,<3
  - pydantic-core
  - pandas
  - sra-tools
  - pigz
  - pysradb
  - kb-python
  - scipy<1.14
  - scanpy
  - scikit-misc
  - igraph
  - leidenalg
  - scvelo
  - mygene
  - biothings_client
  - anysqlite
  - hishel==0.1.3
  - matplotlib-base<3.8
  - setuptools<81
  - pip:
      - torch
      - dynamo-release
      - velovi
      - torchdiffeq
      - scvi-tools
